-------------------
--커뮤니티 DDL
-------------------
--기존 테이블 삭제
DROP TABLE BOARD;
DROP TABLE BORADREPLY;
DROP TABLE FASHION;
DROP TABLE FASHIONREPLY;
DROP TABLE FOOD;
DROP TABLE FOODREPLY;
DROP TABLE FOODP;
DROP TABLE FOODPREPLY;
DROP TABLE HOUSING;
DROP TABLE HOUSINGREPLY;
DROP TABLE HOUSINGP;
DROP TABLE HOUSINGPREPLY;
DROP TABLE FOOD_REPLY;
DROP TABLE HOUSING_REPLY;

DROP SEQUENCE SEQ_B_NO;
DROP SEQUENCE SEQ_B_R_NO;
DROP SEQUENCE SEQ_F_NO;
DROP SEQUENCE SEQ_F_R_NO;
DROP SEQUENCE SEQ_FD_NO;
DROP SEQUENCE SEQ_FD_R_NO;
DROP SEQUENCE SEQ_FDP_NO;
DROP SEQUENCE SEQ_FDP_R_NO;
DROP SEQUENCE SEQ_H_NO;
DROP SEQUENCE SEQ_H_R_NO;
DROP SEQUENCE SEQ_HP_NO;
DROP SEQUENCE SEQ_HP_R_NO;

INCREMENT BY 1 --증감숫자 1
START WITH 1 --시작숫자 1
MINVALUE 1 --최소값 1
MAXVALUE 1000; --최대값 1000
-- 패션게시판 작성
CREATE TABLE BOARD(
    B_NO NUMBER PRIMARY KEY,
    B_WRITER VARCHAR2(20) NOT NULL,
    B_TITLE VARCHAR2(100) NOT NULL,
    B_CONTENT VARCHAR2(1000) NOT NULL,
    B_DATE DATE DEFAULT SYSDATE,
    B_COUNT NUMBER(3)  DEFAULT 0,
    B_STATUS VARCHAR2(2) DEFAULT 'Y',
    B_ORIGIN VARCHAR2(255),
    B_CHANGE VARCHAR2(255) 
);


CREATE TABLE BORADREPLY(
   B_R_NO   NUMBER PRIMARY KEY,
   B_R_BNO    NUMBER NOT NULL,
   B_R_WRITER  VARCHAR2(20) NOT NULL,
   B_R_CONTENT VARCHAR2(500) NOT NULL,
   B_R_CREATE  DATE DEFAULT SYSDATE,
   B_R_STATUS  VARCHAR2(2) DEFAULT 'Y'
);

CREATE TABLE FASHION(
    F_NO NUMBER PRIMARY KEY,
    F_WRITER VARCHAR2(20) NOT NULL,
    F_TITLE VARCHAR2(100) NOT NULL,
    F_CONTENT VARCHAR2(1000) NOT NULL,
    F_DATE DATE DEFAULT SYSDATE,
    F_COUNT NUMBER(3)  DEFAULT 0,
    F_STATUS VARCHAR2(2) DEFAULT 'Y',
    F_ORIGIN VARCHAR2(255),
    F_CHANGE VARCHAR2(255) 
);


CREATE TABLE FASHIONREPLY(
   F_R_NO   NUMBER PRIMARY KEY,
   F_R_BNO    NUMBER NOT NULL,
   F_R_WRITER  VARCHAR2(20) NOT NULL,
   F_R_CONTENT VARCHAR2(500) NOT NULL,
   F_R_CREATE  DATE DEFAULT SYSDATE,
   F_R_STATUS  VARCHAR2(2) DEFAULT 'Y'
);

-- 푸드게시판
CREATE TABLE FOOD(
    FD_NO NUMBER PRIMARY KEY,
    FD_WRITER VARCHAR2(20) NOT NULL,
    FD_TITLE VARCHAR2(100) NOT NULL,
    FD_CONTENT VARCHAR2(1000) NOT NULL,
    FD_DATE DATE DEFAULT SYSDATE,
    FD_COUNT NUMBER(3)  DEFAULT 0,
    FD_STATUS VARCHAR2(2) DEFAULT 'Y',
    FD_ORIGIN VARCHAR2(255),
    FD_CHANGE VARCHAR2(255) 
);

CREATE TABLE FOODREPLY(
   FD_R_NO   NUMBER PRIMARY KEY,
   FD_R_BNO    NUMBER NOT NULL,
   FD_R_WRITER  VARCHAR2(20) NOT NULL,
   FD_R_CONTENT VARCHAR2(500) NOT NULL,
   FD_R_CREATE  DATE DEFAULT SYSDATE,
   FD_R_STATUS  VARCHAR2(2) DEFAULT 'Y'
);

CREATE TABLE FOODP(
    FDP_NO NUMBER PRIMARY KEY,
    FDP_WRITER VARCHAR2(20) NOT NULL,
    FDP_TITLE VARCHAR2(100) NOT NULL,
    FDP_CONTENT VARCHAR2(1000) NOT NULL,
    FDP_DATE DATE DEFAULT SYSDATE,
    FDP_COUNT NUMBER(3)  DEFAULT 0,
    FDP_STATUS VARCHAR2(2) DEFAULT 'Y',
    FDP_ORIGIN VARCHAR2(255),
    FDP_CHANGE VARCHAR2(255) 
);

CREATE TABLE FOODPREPLY(
   FDP_R_NO   NUMBER PRIMARY KEY,
   FDP_R_BNO    NUMBER NOT NULL,
   FDP_R_WRITER  VARCHAR2(20) NOT NULL,
   FDP_R_CONTENT VARCHAR2(500) NOT NULL,
   FDP_R_CREATE  DATE DEFAULT SYSDATE,
   FDP_R_STATUS  VARCHAR2(2) DEFAULT 'Y'
);

--가구 게시판 
CREATE TABLE HOUSING(
    H_NO NUMBER PRIMARY KEY,
    H_WRITER VARCHAR2(20) NOT NULL,
    h_TITLE VARCHAR2(100) NOT NULL,
    H_CONTENT VARCHAR2(1000) NOT NULL,
    H_DATE DATE DEFAULT SYSDATE,
    H_COUNT NUMBER(3)  DEFAULT 0,
    H_STATUS VARCHAR2(2) DEFAULT 'Y',
    H_ORIGIN VARCHAR2(255),
    H_CHANGE VARCHAR2(255) 
);

CREATE TABLE HOUSINGREPLY(
   H_R_NO   NUMBER PRIMARY KEY,
   H_R_BNO    NUMBER NOT NULL,
   H_R_WRITER  VARCHAR2(20) NOT NULL,
   H_R_CONTENT VARCHAR2(500) NOT NULL,
   H_R_CREATE  DATE DEFAULT SYSDATE,
   H_R_STATUS  VARCHAR2(2) DEFAULT 'Y'
);

CREATE TABLE HOUSINGP(
    HP_NO NUMBER PRIMARY KEY,
    HP_WRITER VARCHAR2(20) NOT NULL,
    HP_TITLE VARCHAR2(100) NOT NULL,
    HP_CONTENT VARCHAR2(1000) NOT NULL,
    HP_DATE DATE DEFAULT SYSDATE,
    HP_COUNT NUMBER(3)  DEFAULT 0,
    HP_STATUS VARCHAR2(2) DEFAULT 'Y',
    HP_ORIGIN VARCHAR2(255),
    HP_CHANGE VARCHAR2(255) 
);

CREATE TABLE HOUSINGPREPLY(
   HP_R_NO   NUMBER PRIMARY KEY,
   HP_R_BNO    NUMBER NOT NULL,
   HP_R_WRITER  VARCHAR2(20) NOT NULL,
   HP_R_CONTENT VARCHAR2(500) NOT NULL,
   HP_R_CREATE  DATE DEFAULT SYSDATE,
   HP_R_STATUS  VARCHAR2(2) DEFAULT 'Y'
);



CREATE SEQUENCE SEQ_B_NO;
CREATE SEQUENCE SEQ_B_R_NO;
CREATE SEQUENCE SEQ_F_NO;
CREATE SEQUENCE SEQ_F_R_NO;
CREATE SEQUENCE SEQ_FD_NO;
CREATE SEQUENCE SEQ_FD_R_NO;
CREATE SEQUENCE SEQ_FDP_NO;
CREATE SEQUENCE SEQ_FDP_R_NO;
CREATE SEQUENCE SEQ_H_NO;
CREATE SEQUENCE SEQ_H_R_NO;
CREATE SEQUENCE SEQ_HP_NO;
CREATE SEQUENCE SEQ_HP_R_NO;
