-------------------
--공동구매 DDL
-------------------

--기존 테이블, 시퀀스 모두 삭제
DROP TABLE GB_PURCHASE_HISTORY;
DROP TABLE GB_PRODUCT;
DROP TABLE GROUP_BUYING;
DROP SEQUENCE SEQ_GB_NO;
DROP SEQUENCE SEQ_PRODUCT_NO;
DROP SEQUENCE SEQ_GB_PURCHASE_NO;

--공동구매 게시물 테이블 & 시퀀스
CREATE TABLE GROUP_BUYING (
  GB_NO NUMBER(3) PRIMARY KEY,
  GB_MNO VARCHAR2(20) NOT NULL REFERENCES MEMBER(USER_ID),
  GB_TITLE VARCHAR2(50) NOT NULL,
  GB_CONTENT VARCHAR2(500),
  GB_DATE DATE DEFAULT SYSDATE,
  GB_COUNT NUMBER(3) DEFAULT 0,
  GB_STATUS VARCHAR2(2) DEFAULT 'Y' CHECK(GB_STATUS IN('Y','N')),
  GB_ORIGIN_NAME VARCHAR2(255),
  GB_CHANGE_NAME VARCHAR2(255)
);
CREATE SEQUENCE SEQ_GB_NO;

--공동구매 거래물품 테이블 & 시퀀스
CREATE TABLE GB_PRODUCT(
    PRODUCT_NO NUMBER(3) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    PRODUCT_PRICE VARCHAR2(50),
    PRODUCT_LIMIT VARCHAR2(50),
    PRODUCT_DATE DATE DEFAULT SYSDATE,
    PRODUCT_CNO NUMBER(3) REFERENCES GROUP_BUYING(GB_NO),
    PRODUCT_PURCHASE NUMBER DEFAULT 0
);
ALTER TABLE GB_PRODUCT ADD(PRODUCT_STATUS VARCHAR2(1) DEFAULT 'Y');
ALTER TABLE GB_PRODUCT ADD(PRODUCT_MAX_PURCHASE NUMBER DEFAULT 1);
ALTER TABLE GB_PRODUCT ADD(PRODUCT_ACCOUNT_NUMBER VARCHAR2(100));
ALTER TABLE GB_PRODUCT RENAME COLUMN PRODUCT_ACCOUNT_NUMBER TO PRODUCT_ACCOUNT;
CREATE SEQUENCE SEQ_PRODUCT_NO;

--공동구매 거래기록 테이블 & 시퀀스
CREATE TABLE GB_PURCHASE_HISTORY(
    PH_NO NUMBER PRIMARY KEY,
    PH_PRODUCT NUMBER(3) NOT NULL REFERENCES GB_PRODUCT(PRODUCT_NO),
    PH_QUANTITY NUMBER DEFAULT 0,
    PH_CNO NUMBER(3) REFERENCES GROUP_BUYING(GB_NO),
    PH_BUYER VARCHAR2(20) REFERENCES MEMBER(USER_ID),
    PH_BUYER_NAME VARCHAR2(100) NOT NULL,
    PH_SELLER VARCHAR2(20) REFERENCES MEMBER(USER_ID),
    PH_RECORD_DATE DATE DEFAULT SYSDATE,
    PH_CHANGE_DATE DATE DEFAULT SYSDATE,
    PH_ADDRESS VARCHAR2(200) NOT NULL,
    PH_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(PH_STATUS IN ('Y','N'))
);
CREATE SEQUENCE SEQ_GB_PURCHASE_NO;
ALTER TABLE GB_PURCHASE_HISTORY ADD(PH_SALES_STATUS VARCHAR2(1) DEFAULT 'W' CHECK (PH_SALES_STATUS IN ('W','R','C')));
ALTER TABLE GB_PURCHASE_HISTORY ADD(PH_INVOICE VARCHAR2(200) DEFAULT 'N/A');
COMMIT;