----------------------
--중고거래 DDL
-----------------------

CREATE SEQUENCE SEQ_UNO --게시물번호 시퀀스
INCREMENT BY 1 --증감숫자 1
START WITH 1 --시작숫자 1
MINVALUE 1 --최소값 1
MAXVALUE 1000; --최대값 1000

CREATE TABLE "USEDMARKET" (
   "UM_NO"   NUMBER      NOT NULL,
   "UM_TITLE"   VARCHAR2(100)      NULL,
   "UM_CONTENT"   VARCHAR2(1000)      NOT NULL,
   "UM_WRITER"   VARCHAR2(20)      NOT NULL,
   "UM_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "UM_VIEW_COUNT"   NUMBER   DEFAULT 0   NOT NULL,
   "UM_CATEGORY"   VARCHAR2(50)      NOT NULL,
   "UM_SYSTEM"   VARCHAR2(50)      NOT NULL,
   "UM_STATUS"   VARCHAR2(1)   DEFAULT 'Y'   NOT NULL,
   "UM_PRICE"   NUMBER      NOT NULL,
   "ORIGIN_NAME"   VARCHAR2(300)      NULL,
   "CHANGE_NAME"   VARCHAR2(300)      NULL
);

ALTER TABLE "USEDMARKET" ADD CONSTRAINT "PK_USEDMARKET" PRIMARY KEY (
   "UM_NO"
);


COMMIT;